In [15]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [16]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [17]:
downloaded = drive.CreateFile({'id':'1uEIqviPLtJn9vb7lxrtPSKoaPKgOyE7G'}) # replace the id with id of file you want to access
downloaded.GetContentFile('roster_data_sample.json')

In [18]:
#  code: http://www.py4e.com/code3/roster/roster.py
import json
import sqlite3

conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()
 
# Do some setup
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;
 
CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);
 
CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);
 
CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''')
 
fname = input('Enter file name: ')
if len(fname) < 1:
    fname = 'roster_data_sample.json'
str_data = open(fname).read()
json_data = json.loads(str_data)
 
for entry in json_data:
    name = entry[0];
    title = entry[1];
    role = entry[2];
    print((name, title, role))
 
    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES ( ? )''', ( name, ) )
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]
 
    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES ( ? )''', ( title, ) )
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]
 
    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id, role) VALUES ( ?, ?, ? )''',
        ( user_id, course_id, role ) )
 
conn.commit()
 
test_statement = """
SELECT hex(User.name || Course.title || Member.role ) AS X FROM 
    User JOIN Member JOIN Course 
    ON User.id = Member.user_id AND Member.course_id = Course.id
    ORDER BY X
"""
cur.execute(test_statement)
result = cur.fetchone()
print("RESULT: " + str(result))
 
#Closing the connection
cur.close()
conn.close()

Enter file name: roster_data_sample.json
('Charley', 'si110', 1)
('Mea', 'si110', 0)
('Hattie', 'si110', 0)
('Lyena', 'si110', 0)
('Keziah', 'si110', 0)
('Ellyce', 'si110', 0)
('Thalia', 'si110', 0)
('Meabh', 'si110', 0)
('Aria', 'si110', 0)
('Reena', 'si110', 0)
('Ioannis', 'si110', 0)
('Reily', 'si110', 0)
('Sidharth', 'si110', 0)
('Keiara', 'si110', 0)
('Yann', 'si110', 0)
('Marykate', 'si110', 0)
('Dylan', 'si110', 0)
('Kiran', 'si110', 0)
('Faizaan', 'si110', 0)
('Aneshia', 'si110', 0)
('Kamron', 'si110', 0)
('Allen', 'si110', 0)
('Marshall', 'si110', 0)
('Rosa', 'si106', 1)
('Nora', 'si106', 0)
('Mairin', 'si106', 0)
('Zendel', 'si106', 0)
('Honie', 'si106', 0)
('Betsy', 'si106', 0)
('Davie', 'si106', 0)
('Larissa', 'si106', 0)
('Shaurya', 'si106', 0)
('Shania', 'si106', 0)
('Sorcha', 'si106', 0)
('Jeanna', 'si106', 0)
('Temba', 'si106', 0)
('Buse', 'si106', 0)
('Mohammed', 'si106', 0)
('Kayah', 'si106', 0)
('Kareena', 'si106', 0)
('Dineo', 'si106', 0)
('Philippa', 'si106', 0)
('Lia', 'si206', 1)
('Sharlyn', 'si206', 0)
('Linton', 'si206', 0)
('Temilade', 'si206', 0)
('Areez', 'si206', 0)
('MacCartney', 'si206', 0)
('Abubakar', 'si206', 0)
('Derryn', 'si206', 0)
('Elan', 'si206', 0)
('Vikki', 'si206', 0)
('Anisa', 'si206', 0)
('Klevis', 'si206', 0)
('Tait', 'si206', 0)
('Rhea', 'si206', 0)
('Pearsen', 'si206', 0)
('Willow', 'si206', 0)
('Skye', 'si206', 0)
('Caralee', 'si206', 0)
('Charlee', 'si206', 0)
('Karyn', 'si206', 0)
('Elana', 'si206', 0)
('Maggie', 'si206', 0)
('Eryk', 'si206', 0)
('Zulaikha', 'si301', 1)
('Elshan', 'si301', 0)
('Anastasia', 'si301', 0)
('Connar', 'si301', 0)
('Anay', 'si301', 0)
('Jayla', 'si301', 0)
('Cai', 'si301', 0)
('Zijie', 'si301', 0)
('Riana', 'si301', 0)
('Codie', 'si301', 0)
('Colette', 'si301', 0)
('Lucee', 'si301', 0)
('Tatiana', 'si301', 0)
('Zhong', 'si301', 0)
('Lowri', 'si301', 0)
('Maggy', 'si301', 0)
('Basher', 'si301', 0)
('Tanika', 'si301', 0)
('Aria', 'si301', 0)
('Belle', 'si301', 0)
('Laranya', 'si301', 0)
('Dayna', 'si301', 0)
('Elleanne', 'si301', 0)
('Maanav', 'si310', 1)
('Tamta', 'si310', 0)
('Frazer', 'si310', 0)
('Sacha', 'si310', 0)
('Aidan', 'si310', 0)
('Abel', 'si310', 0)
('Ahtasham', 'si310', 0)
('Avinash', 'si310', 0)
('Colette', 'si310', 0)
('Cohen', 'si310', 0)
('Rori', 'si310', 0)
('Youer', 'si310', 0)
('Jamey', 'si310', 0)
('Makenzie', 'si310', 0)
('Ida', 'si310', 0)
('Alexzander', 'si310', 0)
('Kavita', 'si310', 0)
('Talia', 'si310', 0)
('Anthony', 'si310', 0)
('Elona', 'si334', 1)
('Inan', 'si334', 0)
('Caoilainn', 'si334', 0)
('Ainsley', 'si334', 0)
('Franciszek', 'si334', 0)
('Corrie', 'si334', 0)
('Nolan', 'si334', 0)
('Makala', 'si334', 0)
('Obieluem', 'si334', 0)
('Camryn', 'si334', 0)
('Honie', 'si334', 0)
('Ole', 'si334', 0)
('Raine', 'si334', 0)
('Tyllor', 'si334', 0)
('Diane', 'si334', 0)
('Cullen', 'si334', 0)
('Taylor', 'si334', 0)
('Schekina', 'si334', 0)
('Kensey', 'si334', 0)
('Zhi', 'si334', 0)
('Kiran', 'si334', 0)
('Tymoteusz', 'si334', 0)
('Windsor', 'si363', 1)
('Kashish', 'si363', 0)
('Diarmid', 'si363', 0)
('Laura', 'si363', 0)
('Jaskaran', 'si363', 0)
('Presley', 'si363', 0)
('Brooklynn', 'si363', 0)
('Heddle', 'si363', 0)
('Travis', 'si363', 0)
('Alx', 'si363', 0)
('Airen', 'si363', 0)
('Erika', 'si363', 0)
('Mackie', 'si363', 0)
('Wen', 'si363', 0)
('Seaan', 'si363', 0)
('Meghan', 'si363', 0)
('Ryaan', 'si363', 0)
('Imogem', 'si364', 1)
('Harlie', 'si364', 0)
('Ronnie', 'si364', 0)
('Lucca', 'si364', 0)
('Shanelle', 'si364', 0)
('Ieuan', 'si364', 0)
('Anneliese', 'si364', 0)
('Simon', 'si364', 0)
('Sorche', 'si364', 0)
('Nawal', 'si364', 0)
('Adelaide', 'si364', 0)
('Rhia', 'si364', 0)
('Katarzyna', 'si364', 0)
('LLeyton', 'si364', 0)
('Enzo', 'si364', 0)
('Declan', 'si364', 0)
('Emelie', 'si364', 0)
('Baillie', 'si364', 0)
('Shola', 'si364', 0)
('Jenna', 'si422', 1)
('Miles', 'si422', 0)
('Sakina', 'si422', 0)
('Melanie', 'si422', 0)
('Bailie', 'si422', 0)
('Cassy', 'si422', 0)
('Nikash', 'si422', 0)
('Hebe', 'si422', 0)
('Sia', 'si422', 0)
('Skyla', 'si422', 0)
('Jamaal', 'si422', 0)
('Keanna', 'si422', 0)
('Vanya', 'si422', 0)
('Temperance', 'si422', 0)
('Hafiza', 'si422', 0)
('Alx', 'si422', 0)
('Brigitte', 'si422', 0)
('Eliana', 'si422', 0)
('Kayden', 'si422', 0)
('Man', 'si422', 0)
('Jaydyn', 'si422', 0)
('Soukina', 'si430', 1)
('Stephenjunior', 'si430', 0)
('Buddy', 'si430', 0)
('Holly', 'si430', 0)
('Kamilia', 'si430', 0)
('Cassie', 'si430', 0)
('Kris', 'si430', 0)
('Maia', 'si430', 0)
('Abel', 'si430', 0)
('Tamika', 'si430', 0)
('Deano', 'si430', 0)
('Rosa', 'si430', 0)
('Georgia', 'si430', 0)
('Louie', 'si430', 0)
('Kassie', 'si430', 0)
('Mutinta', 'si430', 0)
('Manwen', 'si430', 0)
RESULT: ('4162656C736933313030',)